apiVersion : apps/v1
kind: Deployment
metadata:
  name: springbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp 
    spec:
      containers:
        - name: springbootapp 
          image: 646383417780.dkr.ecr.eu-west-1.amazonaws.com/first_repo:latest
          ports:
          - containerPort: 80
